name: OnPushVersion

on:
  push:
    branches: [ master ]  
    tags:
    - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
   
      - name: Setup NodeJs 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Install Pkg
        run: npm install -g pkg
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}       
      - name: Build
        run: |
          npm run build
          npm run pkgAll
      - name: Zip exe
        uses: vimtor/action-zip@v1
        with:
          files: stserveruploader.exe
          dest: stserveruploader.zip
      - name: Zip linux executable
        run: |
          tar -zcvf stserveruploader.gz ./stserveruploader.run

      - name: Upload to github Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./stserveruploader.zip
          asset_name: stserveruploader.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "stserveruploader"

      - name: Upload to github Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./stserveruploader.gz
          asset_name: stserveruploader.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: "stserveruploader"
